---
title: "Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
data("instacart")
```

```{r tidy_data}
set.seed(1)
inst = 
  instacart %>% 
janitor::clean_names() %>% 
sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### order counts of different departments

```{r warning = FALSE}
  inst %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department,n)) %>%
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")
```

Column {data-width=550}
-----------------------------------------------------------------------

### Distribution of averanges days since prior order and count of department

```{r warning = FALSE}
line = 
inst %>% 
  group_by(department) %>% 
  summarise(
    ave_day = mean(days_since_prior_order),
    count = n()
  ) %>% 
  mutate(department = fct_reorder(department,desc(ave_day))) %>% 
  ggplot(aes(x = department,y = ave_day,color = count))+
  geom_point() +
  theme(axis.text.x = element_text(angle = 90, size = 5.5),
        axis.title = element_text(size = 5.5)
        )+
  labs(
    y = "Average days since prior order"
  )
ggplotly(line)

```

### Distribution of order numbers in each hour of the day in the day of the week 

```{r}
  box =
  inst %>% 
  group_by(order_dow,order_hour_of_day) %>% 
  summarise(
    count = n()
  ) %>% 
  ggplot(aes(x = as.factor(order_hour_of_day), y = count))+
  geom_boxplot()+
  labs(
      x = "Hour in the day",
      y = "Count"
    ) 
ggplotly(box)

```





